title: Altug Aksoy, PhD
description: Atmospheric Scientist | Tropical Cyclones & Data Assimilation
remote_theme: pages-themes/minimal@v0.2.0 # A clean, scientific look
google_analytics: # You can add your ID here later
show_downloads: true
kramdown:
  math_engine: mathjax
