title: Altug Aksoy, PhD
logo: /favicon.png
description: >
  Atmospheric Scientist | Tropical Cyclones & Data Assimilation
  <br><br>
  [Google Scholar](https://scholar.google.com/citations?user=YOUR_ID_HERE)  
  [ORCID](https://orcid.org/0000-0002-2335-7710)  
  [Email](mailto:aaksoy@miami.edu)
github_username: hailcloud-um
remote_theme: pages-themes/minimal@v0.2.0
